# Generated by Django 5.2.16 on 2026-08-12 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DocumentationItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('category', models.CharField(choices=[('quick_start', 'Quick Start'), ('video_tutorial', 'Video Tutorial'), ('module_guide', 'Module Guide')], default='quick_start', max_length=50)),
                ('url', models.URLField(blank=True, help_text='External link to documentation or video', null=True)),
                ('thumbnail_url', models.URLField(blank=True, help_text='Thumbnail image URL for video', null=True)),
                ('video_file', models.FileField(blank=True, help_text='Upload local video file', null=True, upload_to='documentation_videos/')),
                ('order', models.IntegerField(default=0, help_text='Order in which it appears in the side panel')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['category', 'order', '-created_at'],
            },
        ),
    ]
