# Generated by Django 6.0.6 on 2026-06-05 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access_control', '0001_initial'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AppModule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('module_order', models.IntegerField(default=0)),
            ],
            options={
                'db_table': 'app_modules',
            },
        ),
        migrations.CreateModel(
            name='AppFeature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feature_key', models.CharField(max_length=100, unique=True)),
                ('label', models.CharField(max_length=100)),
                ('module', models.ForeignKey(db_column='module_id', on_delete=django.db.models.deletion.CASCADE, to='setups.appmodule')),
            ],
            options={
                'db_table': 'app_features',
            },
        ),
        migrations.CreateModel(
            name='RoleAccessMapping',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permissions', models.JSONField(blank=True, default=dict)),
                ('department', models.ForeignKey(blank=True, db_column='department_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='organizations.department')),
                ('role', models.ForeignKey(db_column='role_id', on_delete=django.db.models.deletion.CASCADE, to='access_control.role')),
            ],
            options={
                'db_table': 'role_access_mappings',
                'unique_together': {('role', 'department')},
            },
        ),
    ]
