# Generated by Django 5.2.16 on 2026-07-17 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setups', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryMasterField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('field_type', models.CharField(choices=[('request_type', 'Request Type'), ('budget_head', 'Budget Head'), ('tower', 'Tower'), ('floor', 'Floor'), ('category', 'Category')], max_length=50)),
                ('value', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=100)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'inventory_master_fields',
                'unique_together': {('field_type', 'value')},
            },
        ),
    ]
