# Generated by Django 6.0.6 on 2026-06-05 11:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkflowRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('min_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('max_amount', models.DecimalField(decimal_places=2, default=999999999.99, max_digits=15)),
                ('department_id', models.IntegerField(blank=True, null=True)),
                ('required_role_name', models.CharField(max_length=100)),
                ('step_sequence', models.IntegerField(default=1)),
                ('sla_hours', models.IntegerField(default=24)),
                ('conditional_type', models.CharField(default='always', max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'workflow_rules',
            },
        ),
        migrations.CreateModel(
            name='WorkflowInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module', models.CharField(max_length=100)),
                ('entity_id', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'workflow_instances',
                'unique_together': {('module', 'entity_id')},
            },
        ),
        migrations.CreateModel(
            name='WorkflowStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_sequence', models.IntegerField()),
                ('assigned_role_name', models.CharField(max_length=100)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('sla_hours', models.IntegerField(default=24)),
                ('due_at', models.DateTimeField()),
                ('actioned_at', models.DateTimeField(blank=True, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('escalated_to_role', models.CharField(blank=True, max_length=100, null=True)),
                ('actioned_by', models.ForeignKey(blank=True, db_column='actioned_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='actioned_steps', to=settings.AUTH_USER_MODEL)),
                ('assigned_user', models.ForeignKey(blank=True, db_column='assigned_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_steps', to=settings.AUTH_USER_MODEL)),
                ('instance', models.ForeignKey(db_column='instance_id', on_delete=django.db.models.deletion.CASCADE, to='workflows.workflowinstance')),
            ],
            options={
                'db_table': 'workflow_steps',
            },
        ),
    ]
