# Generated by Django 6.0.6 on 2026-06-09 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_department_approval_limit_department_budget_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='site',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='site',
            name='longitude',
        ),
        migrations.AddField(
            model_name='site',
            name='site_manager_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='site',
            name='site_manager_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
