# Generated by Django 6.0.6 on 2026-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GRN',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('po_id', models.CharField(max_length=50)),
                ('received_date', models.DateField()),
                ('received_by', models.CharField(max_length=100)),
                ('items', models.JSONField(default=list)),
                ('status', models.CharField(default='received', max_length=50)),
                ('invoice_status', models.CharField(default='pending', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'grns',
            },
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('uom', models.CharField(max_length=50)),
                ('min_stock_level', models.IntegerField(default=0)),
                ('reorder_level', models.IntegerField(default=0)),
                ('current_stock', models.IntegerField(default=0)),
                ('preferred_vendor', models.CharField(blank=True, max_length=50, null=True)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'items',
            },
        ),
        migrations.CreateModel(
            name='MaterialIssue',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('items', models.JSONField(default=list)),
                ('issued_to', models.CharField(max_length=100)),
                ('issued_date', models.DateField()),
                ('tower', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('purpose', models.TextField()),
                ('status', models.CharField(default='issued', max_length=50)),
                ('department', models.CharField(blank=True, max_length=100, null=True)),
                ('work_order_ref', models.CharField(blank=True, max_length=50, null=True)),
                ('issued_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'material_issues',
            },
        ),
        migrations.CreateModel(
            name='ScrapDisposal',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('items', models.JSONField(default=list)),
                ('total_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('disposal_date', models.DateField()),
                ('buyer', models.CharField(max_length=255)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('gate_pass_no', models.CharField(blank=True, max_length=50, null=True)),
                ('recovered_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'scrap_disposals',
            },
        ),
        migrations.CreateModel(
            name='StockTransfer',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('from_location', models.CharField(max_length=100)),
                ('to_location', models.CharField(max_length=100)),
                ('items', models.JSONField(default=list)),
                ('requested_by', models.CharField(max_length=100)),
                ('requested_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('transfer_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'stock_transfers',
            },
        ),
    ]
