# Generated by Django 6.0.6 on 2026-06-18 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0002_grn_invoice_number_grn_remarks_grn_vendor_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='GoodsDispatchNote',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('grn_id', models.CharField(max_length=50)),
                ('destination', models.CharField(max_length=255)),
                ('items', models.JSONField(default=list)),
                ('status', models.CharField(default='dispatched', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'goods_dispatch_notes',
            },
        ),
        migrations.CreateModel(
            name='ReturnToVendor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('grn_id', models.CharField(max_length=50)),
                ('vendor_reference', models.CharField(max_length=255)),
                ('items', models.JSONField(default=list)),
                ('reason', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='returned', max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'returns_to_vendor',
            },
        ),
        migrations.AlterField(
            model_name='grn',
            name='status',
            field=models.CharField(default='pending', max_length=50),
        ),
    ]
