# Generated by Django 6.0.6 on 2026-06-18 12:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0003_goodsdispatchnote_returntovendor_alter_grn_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLedger',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('transaction_type', models.CharField(choices=[('GRN_RECEIPT', 'GRN Receipt'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('RETURN_FROM_SITE', 'Return From Site'), ('GOODS_ISSUE', 'Goods Issue')], max_length=50)),
                ('quantity', models.IntegerField()),
                ('stock_before', models.IntegerField()),
                ('stock_after', models.IntegerField()),
                ('reason', models.CharField(blank=True, max_length=255, null=True)),
                ('reference_number', models.CharField(blank=True, max_length=255, null=True)),
                ('remarks', models.TextField()),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='inventory.item')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'stock_ledger',
                'ordering': ['-timestamp'],
            },
        ),
    ]
