# Generated by Django 6.0.6 on 2026-06-19 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_stockledger'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockledger',
            name='source_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='stockledger',
            name='source_type',
            field=models.CharField(blank=True, choices=[('GRN', 'Goods Receipt Note'), ('GDN', 'Goods Dispatch Note'), ('RTV', 'Return To Vendor'), ('MANUAL', 'Manual Entry')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='transaction_type',
            field=models.CharField(choices=[('GRN_RECEIPT', 'GRN Receipt'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('RETURN_FROM_SITE', 'Return From Site'), ('GOODS_ISSUE', 'Goods Issue'), ('RETURN_TO_VENDOR', 'Return To Vendor')], max_length=50),
        ),
    ]
