# Generated by Django 6.0.6 on 2026-06-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0005_stockledger_source_id_stockledger_source_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockledger',
            name='source_type',
            field=models.CharField(blank=True, choices=[('GRN', 'Goods Receipt Note'), ('GDN', 'Goods Dispatch Note'), ('RTV', 'Return To Vendor'), ('MANUAL', 'Manual Entry'), ('SYSTEM', 'System Entry')], max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='stockledger',
            name='transaction_type',
            field=models.CharField(choices=[('GRN_RECEIPT', 'GRN Receipt'), ('MANUAL_ADJUSTMENT', 'Manual Adjustment'), ('RETURN_FROM_SITE', 'Return From Site'), ('GOODS_ISSUE', 'Goods Issue'), ('RETURN_TO_VENDOR', 'Return To Vendor'), ('OPENING_BALANCE', 'Opening Balance')], max_length=50),
        ),
    ]
