# Generated by Django 6.0.6 on 2026-06-22 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0006_alter_stockledger_source_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='inspected_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='grn',
            name='inspected_by',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
