# Generated by Django 6.0.6 on 2026-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0007_grn_inspected_at_grn_inspected_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='grn',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='grn',
            name='invoice_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
