# Generated by Django 5.2.16 on 2026-07-17 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0008_grn_attachments_grn_invoice_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductInspection',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('po_id', models.CharField(max_length=50)),
                ('vendor_name', models.CharField(blank=True, default='', max_length=255)),
                ('received_date', models.DateField()),
                ('inspector_name', models.CharField(max_length=100)),
                ('items', models.JSONField(default=list)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('challan_number', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_number', models.CharField(blank=True, default='', max_length=100)),
                ('invoice_date', models.DateField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, default='')),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'product_inspections',
            },
        ),
    ]
