# Generated by Django 6.0.6 on 2026-06-09 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0002_role_access_level_role_approval_limit_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='rolemodulepermission',
            old_name='can_modify',
            new_name='can_edit',
        ),
    ]
