# Generated by Django 6.0.6 on 2026-06-12 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access_control', '0003_rename_can_modify_rolemodulepermission_can_edit'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='cross_dept_access',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='role',
            name='dashboard_type',
            field=models.CharField(default='Default', max_length=100),
        ),
        migrations.AddField(
            model_name='role',
            name='role_code',
            field=models.CharField(default='', max_length=50),
        ),
    ]
