# Generated by Django 6.0.6 on 2026-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RateContract',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vendor', models.CharField(max_length=255)),
                ('vendor_id', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('service_scope', models.TextField()),
                ('category', models.CharField(max_length=100)),
                ('contract_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('billing_cycle', models.CharField(max_length=50)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('sla_kpis', models.JSONField(default=list)),
                ('status', models.CharField(default='active', max_length=50)),
                ('utilization_percent', models.DecimalField(decimal_places=2, default=0.0, max_digits=5)),
                ('last_billing_date', models.DateField(blank=True, null=True)),
                ('next_billing_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rate_contracts',
            },
        ),
        migrations.CreateModel(
            name='Vendor',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('type', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('gst_number', models.CharField(max_length=50)),
                ('pan', models.CharField(max_length=50)),
                ('msme_status', models.BooleanField(default=False)),
                ('bank_name', models.CharField(max_length=100)),
                ('account_number', models.CharField(max_length=100)),
                ('ifsc', models.CharField(max_length=50)),
                ('sla_rating', models.DecimalField(decimal_places=2, default=0.0, max_digits=3)),
                ('approved_towers', models.JSONField(default=list)),
                ('compliance_expiry', models.DateField()),
                ('status', models.CharField(default='active', max_length=50)),
                ('contact_person', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vendors',
            },
        ),
    ]
