# Generated by Django 6.0.6 on 2026-06-15 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action', models.CharField(max_length=100)),
                ('target_type', models.CharField(max_length=50)),
                ('target_id', models.CharField(max_length=100)),
                ('actioned_by', models.CharField(max_length=100)),
                ('comments', models.TextField(blank=True, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'vendor_audit_logs',
            },
        ),
        migrations.AddField(
            model_name='vendor',
            name='onboarding_status',
            field=models.CharField(default='Account Created', max_length=50),
        ),
        migrations.AddField(
            model_name='vendor',
            name='user_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
