# Generated by Django 6.0.6 on 2026-06-26 07:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vendors', '0002_auditlog_vendor_onboarding_status_vendor_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='vendor',
            name='is_universal_vendor',
            field=models.BooleanField(default=False),
        ),
    ]
