# Generated by Django 6.0.6 on 2026-06-05 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('fy', models.CharField(max_length=50)),
                ('type', models.CharField(max_length=50)),
                ('tower', models.CharField(max_length=50)),
                ('department', models.CharField(max_length=100)),
                ('category', models.CharField(max_length=100)),
                ('gl_code', models.CharField(max_length=100)),
                ('period', models.CharField(max_length=50)),
                ('annual_budget', models.DecimalField(decimal_places=2, max_digits=15)),
                ('allocated', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('committed', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('actual', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('owner', models.CharField(max_length=100)),
                ('status', models.CharField(default='draft', max_length=50)),
                ('notes', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'budgets',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('category', models.CharField(max_length=100)),
                ('amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('date', models.DateField()),
                ('payment_mode', models.CharField(max_length=50)),
                ('status', models.CharField(default='pending', max_length=50)),
                ('description', models.TextField(blank=True, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=100, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'expenses',
            },
        ),
        migrations.CreateModel(
            name='Indent',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('tower', models.CharField(max_length=50)),
                ('floor', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('items', models.JSONField(default=list)),
                ('estimated_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('required_date', models.DateField()),
                ('budget_head', models.CharField(max_length=50)),
                ('justification', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(default=list)),
                ('status', models.CharField(default='submitted', max_length=50)),
                ('created_by', models.CharField(max_length=100)),
                ('approvals', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'indents',
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vendor_id', models.CharField(max_length=50)),
                ('vendor_name', models.CharField(max_length=255)),
                ('invoice_number', models.CharField(max_length=100)),
                ('invoice_date', models.DateField()),
                ('po_id', models.CharField(max_length=50)),
                ('grn_id', models.CharField(blank=True, max_length=50, null=True)),
                ('ses_id', models.CharField(blank=True, max_length=50, null=True)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('gst', models.DecimalField(decimal_places=2, max_digits=15)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='pending', max_length=50)),
                ('matching_status', models.CharField(default='2way', max_length=50)),
                ('attachments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'invoices',
            },
        ),
        migrations.CreateModel(
            name='PaymentProposal',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('vendor_name', models.CharField(max_length=255)),
                ('vendor_id', models.CharField(max_length=50)),
                ('invoices', models.JSONField(default=list)),
                ('total_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('gst_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('retention_amount', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('net_payable', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('due_date', models.DateField()),
                ('status', models.CharField(default='pending_approval', max_length=50)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateField()),
                ('current_approver', models.CharField(blank=True, max_length=100, null=True)),
                ('approval_level', models.IntegerField(default=1)),
                ('max_approval_level', models.IntegerField(default=1)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'payment_proposals',
            },
        ),
        migrations.CreateModel(
            name='PurchaseOrder',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('type', models.CharField(max_length=50)),
                ('vendor', models.CharField(max_length=50)),
                ('vendor_name', models.CharField(max_length=255)),
                ('linked_rfq', models.CharField(blank=True, max_length=50, null=True)),
                ('items', models.JSONField(default=list)),
                ('total_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('taxes', models.DecimalField(decimal_places=2, max_digits=15)),
                ('net_value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('retention_percent', models.IntegerField(default=0)),
                ('milestones', models.JSONField(default=list)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('status', models.CharField(default='draft', max_length=50)),
                ('tower', models.CharField(max_length=50)),
                ('category', models.CharField(max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'purchase_orders',
            },
        ),
        migrations.CreateModel(
            name='RFQ',
            fields=[
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('tower', models.CharField(max_length=50)),
                ('linked_pr', models.CharField(blank=True, max_length=50, null=True)),
                ('estimated_value', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('bid_due_date', models.DateField()),
                ('status', models.CharField(default='published', max_length=50)),
                ('vendors', models.JSONField(default=list)),
                ('created_by', models.CharField(max_length=100)),
                ('created_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'rfqs',
            },
        ),
    ]
