# Generated by Django 6.0.6 on 2026-06-09 19:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0002_budget_approval_level_budget_approved_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='purchaseorder',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
