# Generated by Django 6.0.6 on 2026-06-10 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0004_expense_invoice_id_expense_payment_proposal_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Quotation',
            fields=[
                ('status', models.CharField(default='draft', max_length=50)),
                ('current_approver', models.CharField(blank=True, max_length=255, null=True)),
                ('next_role', models.CharField(blank=True, max_length=100, null=True)),
                ('workflow_history', models.JSONField(blank=True, default=list)),
                ('approval_level', models.IntegerField(default=0)),
                ('created_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_by', models.CharField(blank=True, max_length=255, null=True)),
                ('approved_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('rfq_id', models.CharField(max_length=50)),
                ('vendor_id', models.CharField(max_length=50)),
                ('vendor_name', models.CharField(max_length=255)),
                ('base_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('tax_breakdown', models.JSONField(default=dict)),
                ('total_cost', models.DecimalField(decimal_places=2, default=0.0, max_digits=15)),
                ('delivery_timeline', models.CharField(max_length=100)),
                ('warranty', models.CharField(blank=True, max_length=100, null=True)),
                ('vendor_rating', models.DecimalField(decimal_places=2, default=5.0, max_digits=3)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('terms_conditions', models.TextField(blank=True, null=True)),
                ('attachments', models.JSONField(default=list)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'quotations',
            },
        ),
        migrations.AddField(
            model_name='indent',
            name='inventory_recommendation',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='indent',
            name='inventory_status',
            field=models.CharField(default='pending', max_length=50),
        ),
        migrations.AddField(
            model_name='indent',
            name='priority',
            field=models.CharField(default='medium', max_length=50),
        ),
        migrations.AddField(
            model_name='indent',
            name='requisition_type',
            field=models.CharField(default='regular', max_length=50),
        ),
    ]
