# Generated by Django 6.0.6 on 2026-06-11 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0005_quotation_indent_inventory_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='rfq',
            name='recommendation_comments',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='recommended_quotation_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='recommended_vendor_id',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
