# Generated by Django 6.0.6 on 2026-06-15 06:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0006_rfq_recommendation_comments_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quotation',
            name='commercial_advantages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quotation',
            name='commercial_score',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='quotation',
            name='compliance_status',
            field=models.CharField(default='Compliant', max_length=50),
        ),
        migrations.AddField(
            model_name='quotation',
            name='cons',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quotation',
            name='overall_score',
            field=models.IntegerField(default=80),
        ),
        migrations.AddField(
            model_name='quotation',
            name='pros',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quotation',
            name='risks',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quotation',
            name='technical_advantages',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='quotation',
            name='technical_score',
            field=models.IntegerField(default=80),
        ),
    ]
