# Generated by Django 6.0.6 on 2026-06-18 07:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0007_quotation_commercial_advantages_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproposal',
            name='utr_number',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
