# Generated by Django 6.0.6 on 2026-06-23 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0009_budget_rejected_at_budget_rejected_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paymentproposal',
            name='payment_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paymentproposal',
            name='payment_mode',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='paymentproposal',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
