# Generated by Django 6.0.6 on 2026-06-26 07:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0010_paymentproposal_payment_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='paymentproposal',
            name='payment_date',
        ),
        migrations.RemoveField(
            model_name='paymentproposal',
            name='payment_mode',
        ),
        migrations.RemoveField(
            model_name='paymentproposal',
            name='remarks',
        ),
    ]
