# Generated by Django 6.0.6 on 2026-07-03 10:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0013_budgetrevisionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='invoice',
            name='remarks',
            field=models.TextField(blank=True, null=True),
        ),
    ]
