# Generated by Django 5.2.16 on 2026-07-24 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0014_invoice_remarks'),
    ]

    operations = [
        migrations.CreateModel(
            name='BidLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rfq_id', models.CharField(max_length=50)),
                ('vendor_id', models.CharField(max_length=50)),
                ('vendor_name', models.CharField(max_length=255)),
                ('bid_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(default='Valid', max_length=50)),
                ('remarks', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'bid_logs',
            },
        ),
        migrations.AddField(
            model_name='rfq',
            name='auction_end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='rfq',
            name='bidding_type',
            field=models.CharField(default='standard', max_length=50),
        ),
        migrations.AddField(
            model_name='rfq',
            name='reserve_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True),
        ),
    ]
