# Generated by Django 6.0.6 on 2026-06-22 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('approvals', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approvalrequest',
            name='entity_type',
            field=models.CharField(choices=[('indent', 'Indent'), ('purchase_order', 'Purchase Order'), ('grn', 'GRN'), ('invoice', 'Invoice'), ('expense', 'Expense'), ('payment', 'Payment')], max_length=50),
        ),
    ]
